import { ImagePair } from '@/types/quiz'
import real1 from '@/assets/images/real1.png'
import ai1 from '@/assets/images/ai1.png'
import real2 from '@/assets/images/real2.jpg'
import ai2 from '@/assets/images/ai2.jpg'
import real3 from '@/assets/images/real3.jpg'
import ai3 from '@/assets/images/ai3.jpg'
import real4 from '@/assets/images/real4.jpg'
import ai4 from '@/assets/images/ai4.png'
import real5 from '@/assets/images/real5.png'
import ai5 from '@/assets/images/ai5.png'

export const imagePairs: ImagePair[] = [
  {
    id: 1,
    realImage: real1,
    aiImage: ai1,
    explanation: 'Unusual or Inconsistent Details: AI-generated images often contain minor, noticeable detail errors. The blond girl has two forearms and hands on her left side and none on her right, and the paintbrush doesn\'t match up with her hand. Look for abnormalities such as asymmetrical facial features, unusual finger placement, or objects with distorted proportions.'
  },
  {
    id: 2,
    realImage: real2,
    aiImage: ai2,
    explanation: 'Texture and Pattern Repetition: AI sometimes struggles with reproducing complex textures or patterns, resulting in noticeable repetition or awkward transitions. The AI frog\'s spots are overly circular. Look for unnatural patterns in textures, such as hair, skin, clothing, or background elements.'
  },
  {
    id: 3,
    realImage: real3,
    aiImage: ai3,
    explanation: 'Lighting and Shadows: AI-generated images can have inconsistent or unrealistic lighting and shadows. The reflection in the water introduces extra colors not seen in the northern lights in the sky. Check if the lighting on different objects in the image matches and if the shadows are consistent with the light sources.'
  },
  {
    id: 4,
    realImage: real4,
    aiImage: ai4,
    explanation: 'Background Anomalies: Backgrounds in AI images can be a giveaway. Many are overly simplistic, overly complex, or contain elements that don\'t belong. The leaves are overly simplistic and lack detail; furthermore, a simple fact check reveals that the bank in front of Mount Fiji is incorrect as well. Pay attention to the background as much as the main subject.'
  },
  {
    id: 5,
    realImage: real5,
    aiImage: ai5,
    explanation: 'Facial Features: Faces generated by AI can sometimes appear slightly off. This can include oddities in the eyes (like reflections or iris shape), ears, or hair. These features are often subtly surreal or unnaturally symmetrical/asymmetrical. This woman\'s earrings are not the same in each ear, plus there is a single speck of light in the middle of her eyes. Look for unnatural reflections or asymmetrical oddities in features.'
  }
]
